Insert into Categorie (Id_categ , nom) values 
(1, 'Dermatologie'),
(2, 'Digestion et nausées'),
(3, 'Douleurs et fièvres'),
(4, 'Vitamines et minéraux'),
(5, 'Minceur et forme'),
(6, 'Allergies'),
(7, 'Santé et bien-être'),
(8, 'Maman et bébé'),
(9, 'Homéopathie'),
(10, 'Médecines naturelles'),
(11, 'Sexualité'),
(12, 'Orthopédie'),
(13, 'Matériel médical'),
(14, 'Hygiène'),
(15, 'Beauté'),
(16, 'Solaire'),
(17, 'Vétérinaire'),
(18, 'Autres');